### ISSUE TITLE
Division X

### ISSUE THREAD

**Issue by donler** [oddballteam/mac-dc-challenge#5]
## Databricks Cluster Request

Please provide the following information to submit this request:

* Cluster Name: Division X
* Databricks User: DonB
* Number of Worker nodes (Default: 2): 3
* Auto-Termination after creation (Default: 2 hours): 2
* SSH Public Keys (Optional):

**Comment by slapula** [comment]
Cluster Division_X is now ready for use.

If you provided a public SSH key, you can access it using the following SSH command:
`ssh ubuntu@10.31.241.54 -p 2200 -i <private_key_file_path>`
